#!/bin/sh
set -eu
crond
install -o halflife -m 644 /dev/null /halflife.log
su halflife <<':'
    websocketd -port 8888 tail -f /halflife.log &
    cd /home/halflife/SmokeDetector
    python3 ../halflife/halflife.py >/halflife.log 2>&1
:
